'''
Author: Abhijeet Ambekar
Date: 06/26/2023
'''

import os
import logging.config
import joblib
import dvc.api
from model import generate_report
from process_data import process_data

params = dvc.api.params_show()
artifacts_path = params['artifacts-path']
logging.config.fileConfig("log_config.ini")
logger = logging.getLogger()


def evaluate():
    """
    This function evaluates stored model with test data saved
    during process_data step
    """
    try:
        # load the data and labels artifacts generated by processing data
        test = joblib.load(os.path.join(artifacts_path, "test.joblib"))
        X_test, y_test = process_data(test, label='salary')
        model = joblib.load(os.path.join(
            artifacts_path, "model.pkl"))
    except FileNotFoundError:
        logger.error(
            "Artifatcs not found. Please run the process data module first!!")
        return

    y_test_prediction = model.predict(X_test)
    generate_report(
        y_test,
        y_test_prediction,
        "** evaluate **",
        "metrics_evaluate.json")


if __name__ == "__main__":
    evaluate()
