import logging.config
from model import generate_report
import joblib
import dvc.api
import os
params = dvc.api.params_show()
artifacts_path = params['artifacts-path']
logging.config.fileConfig("log_config.ini")
logger = logging.getLogger()


def evaluate():
    try:
        # load the data and labels artifacts generated by processing data
        X_test = joblib.load(os.path.join(
            artifacts_path, "data_test.joblib"))
        y_test = joblib.load(os.path.join(
            artifacts_path, "labels_test.joblib"))

        model = joblib.load(os.path.join(
            artifacts_path, "model.pkl"))
    except FileNotFoundError:
        logger.error(
            "Artifatcs not found. Please run the process data module first!!")
        return

    y_test_prediction = model.predict(X_test)
    generate_report(y_test, y_test_prediction, "metrics_evaluate.json")


if __name__ == "__main__":
    evaluate()
