stages:
  process_data:
    cmd: python ml/process_data.py
    deps:
      - ./ml/process_data.py
      - ./data/census.csv
    outs:
      - ./artifacts/data_train.joblib
      - ./artifacts/labels_train.joblib
      - ./artifacts/data_test.joblib
      - ./artifacts/labels_test.joblib
      - ./artifacts/category_encoder.joblib
      - ./artifacts/binary_encoder.joblib

  train:
    cmd: python ml/train_model.py 
    deps:
      - ./ml/train_model.py
      - ./ml/model.py
      - ./artifacts/data_train.joblib
      - ./artifacts/labels_train.joblib
    outs:
      - ./artifacts/model.pkl
    metrics:
      - ./artifacts/metrics_train.json

  evaluate:
    cmd: python ml/evaluate.py
    deps:
      - ./artifacts/data_test.joblib
      - ./artifacts/labels_test.joblib
      - ./ml/evaluate.py
      - ./ml/model.py
    metrics:
      - ./artifacts/metrics_evaluate.json