name: base-ml-py3.8
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8   
  - scikit-learn
  - pandas
  - numpy
  - pytest
  - jupyter
  - jupyterlab
  - fastapi
  - uvicorn
  - ydata-profiling
  - dvc=3.16.0
  - dvc-gs
  - pylint
  - autopep8
  - gunicorn