name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
        image: aambekar234/base-ml-py3.8:v1.1
        options: --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: store key file
      env:
        MY_SECRET: ${{secrets.SAKEY}}
      run: |
        mkdir keys
        echo "$MY_SECRET" > keys/sa-key.json
        cat keys/sa-key.json

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: keyfile
        path: ./keys/sa-key.json
    - name: Run tests
      run: |
        conda init bash
        . /github/home/.bashrc
        conda activate base-ml-py3.8
        whoami
        pwd
        ls -la
        ls -al keys 
        cat ./keys/sa-key.json
        dvc pull
        pytest

