name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
        image: aambekar234/base-ml-py3.8:v1.1
        options: --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: store key file
      run: |
        mkdir keys
        echo "${{ secrets.SAKEY }}" > sa-key.json
    - name: Run tests
      run: |
        conda init bash
        . /github/home/.bashrc
        conda activate base-ml-py3.8
        whoami
        pwd
        ls -la
        dvc pull
        pytest

