name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
        image: aambekar234/base-ml-py3.8:v1.1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        conda init bash
        source ~/.bashrc
        conda activate base-ml-py3.8
        pytest

