name: Python CI/CD

on:
  push:
    branches:
      - main
env:
  MY_SECRET: ${{secrets.SA_KEY}}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
        image: aambekar234/base-ml-py3.8:v1.1
        options: --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Store google key file for dvc
      shell: bash
      run: |
        mkdir keys
        echo -n "$MY_SECRET" > keys/sa-key.json

    - name: Run tests
      run: |
        conda init bash
        . /github/home/.bashrc
        conda activate base-ml-py3.8
        chown root /__w/ml-income-predict-app/ml-income-predict-app/
        pwd
        dvc pull
        pytest

    - name: Package the app in tar file
      run: tar -cvf app.tar ./

    - name: Upload App directory
      uses: actions/upload-artifact@v3
      with:
        name: app.tar
        path: ./app.tar
        retention-days: 1

  dockerize-app:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:

    - name: Download Packaged App
      uses: actions/download-artifact@v3
      with:
        name: app.tar
        path: ./

    - name: Extract the package
      shell: bash
      run: |
        mkdir app
        tar -xf app.tar -C ./app/
        cd app
        pwd
        ls -la
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: check env
      run: |
        pwd
        ls -la
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./app
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/apps:ml-income-predict-app


