name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
        image: aambekar234/base-ml-py3.8:v1.1
        options: --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        token: ${{ secrets.PAT }}
    - name: store key file
      env:
        MY_SECRET: ${{vars.KEY}}
      shell: bash
      run: |
        mkdir keys
        echo -n "$MY_SECRET" > keys/sa-key.json
        cat keys/sa-key.json

    - name: Run tests
      run: |
        conda init bash
        . /github/home/.bashrc
        conda activate base-ml-py3.8
        whoami
        pwd
        ls -la
        ls -al keys 
        dvc pull
        pytest

